In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

In [4]:
pd.set_option("display.max_columns", 500)
pd.set_option("display.max_rows", 100)

In [5]:
data = pd.read_csv("data/properties_2017.csv", chunksize=50_000)

In [6]:
for i, chunk in enumerate(data):
    if i == 0:
        df = chunk
    break

df.head()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,finishedfloor1squarefeet,calculatedfinishedsquarefeet,finishedsquarefeet12,finishedsquarefeet13,finishedsquarefeet15,finishedsquarefeet50,finishedsquarefeet6,fips,fireplacecnt,fullbathcnt,garagecarcnt,garagetotalsqft,hashottuborspa,heatingorsystemtypeid,latitude,longitude,lotsizesquarefeet,poolcnt,poolsizesum,pooltypeid10,pooltypeid2,pooltypeid7,propertycountylandusecode,propertylandusetypeid,propertyzoningdesc,rawcensustractandblock,regionidcity,regionidcounty,regionidneighborhood,regionidzip,roomcnt,storytypeid,threequarterbathnbr,typeconstructiontypeid,unitcnt,yardbuildingsqft17,yardbuildingsqft26,yearbuilt,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6037,NaN,NaN,NaN,NaN,NaN,NaN,34144442,-118654084,85768.0,NaN,NaN,NaN,NaN,NaN,010D,269,NaN,6.037800e+07,37688.0,3101,NaN,96337.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2016,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6037,NaN,NaN,NaN,NaN,NaN,NaN,34140430,-118625364,4083.0,NaN,NaN,NaN,NaN,NaN,0109,261,LCA11*,6.037800e+07,37688.0,3101,NaN,96337.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27516.0,2015,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,5.0,NaN,NaN,NaN,NaN,73026.0,NaN,NaN,73026.0,NaN,NaN,6037,NaN,NaN,NaN,NaN,NaN,NaN,33989359,-118394633,63085.0,NaN,NaN,NaN,NaN,NaN,1200,47,LAC2,6.037703e+07,51617.0,3101,NaN,96095.0,0.0,NaN,NaN,NaN,2.0,NaN,NaN,1959.0,1.0,NaN,660680.0,1434941.0,2016,774261.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,6.0,NaN,NaN,NaN,5068.0,NaN,NaN,5068.0,NaN,NaN,6037,NaN,NaN,NaN,NaN,NaN,NaN,34148863,-118437206,7521.0,NaN,NaN,NaN,NaN,NaN,1200,47,LAC2,6.037141e+07,12447.0,3101,27080.0,96424.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1948.0,1.0,NaN,580059.0,1174475.0,2016,594416.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,NaN,1776.0,NaN,NaN,1776.0,NaN,NaN,6037,NaN,NaN,NaN,NaN,NaN,NaN,34194168,-118385816,8512.0,NaN,NaN,NaN,NaN,NaN,1210,31,LAM1,6.037123e+07,12447.0,3101,46795.0,96450.0,0.0,NaN,NaN,NaN,1.0,NaN,NaN,1947.0,1.0,NaN,196751.0,440101.0,2016,243350.0,5725.17,NaN,NaN,NaN

In [7]:
df.describe()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,finishedfloor1squarefeet,calculatedfinishedsquarefeet,finishedsquarefeet12,finishedsquarefeet13,finishedsquarefeet15,finishedsquarefeet50,finishedsquarefeet6,fips,fireplacecnt,fullbathcnt,garagecarcnt,garagetotalsqft,heatingorsystemtypeid,latitude,longitude,lotsizesquarefeet,poolcnt,poolsizesum,pooltypeid10,pooltypeid2,pooltypeid7,propertylandusetypeid,rawcensustractandblock,regionidcity,regionidcounty,regionidneighborhood,regionidzip,roomcnt,storytypeid,threequarterbathnbr,typeconstructiontypeid,unitcnt,yardbuildingsqft17,yardbuildingsqft26,yearbuilt,numberofstories,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyyear,censustractandblock
count,5.000000e+04,13953.000000,98.000000,30.000000,50000.000000,50000.000000,258.000000,33080.000000,47896.000000,340.0,3931.000000,49295.000000,45611.000000,158.000000,3203.000000,3931.000000,323.000000,50000.000000,5336.000000,47896.000000,14318.000000,14318.000000,31717.000000,5.000000e+04,5.000000e+04,4.560800e+04,9256.0,500.000000,247.0,513.0,8732.0,50000.00000,5.000000e+04,49049.000000,50000.000000,20109.000000,49824.000000,49999.000000,30.0,5034.000000,102.0,33712.000000,1611.000000,48.000000,49254.000000,11224.000000,4.914000e+04,4.938500e+04,50000.000000,4.895900e+04,4.966300e+04,985.000000,4.859100e+04
mean,1.331894e+07,1.874794,7.244898,582.133333,2.220640,3.077440,3.782946,6.316717,2.317260,66.0,1368.318240,1843.100416,1773.175309,1207.284810,2820.418982,1380.007123,2336.789474,6048.385760,1.165667,2.264177,1.828887,383.325185,4.009900,3.401956e+07,-1.182321e+08,2.352777e+04,1.0,524.060000,1.0,1.0,1.0,259.83678,6.048701e+07,35031.441008,2600.911600,186243.095877,96554.321411,1.434409,7.0,1.010131,6.0,1.175783,316.777157,274.520833,1964.388659,1.393175,1.810380e+05,4.463475e+05,2015.998300,2.685239e+05,5.442323e+03,13.935025,6.048760e+13
std,8.347426e+06,3.045506,2.134939,377.238124,1.100823,1.281903,0.474424,1.739138,1.019712,0.0,633.817509,1712.884612,946.178364,344.763633,5577.321119,672.900079,1524.249238,21.320386,0.465803,1.009676,0.616006,249.529192,3.141686,2.449077e+05,3.540623e+05,1.104410e+05,0.0,167.842434,0.0,0.0,0.0,17.36407,2.116892e+05,52377.681015,766.607769,167830.247580,3862.596645,2.833919,0.0,0.121651,0.0,1.556528,275.009261,283.313374,23.572390,0.532464,4.020174e+05,7.011441e+05,0.074413,4.354585e+05,9.137748e+03,1.526141,2.119249e+11
min,1.071177e+07,1.000000,2.000000,63.000000,0.000000,0.000000,1.000000,1.000000,1.000000,66.0,47.000000,60.000000,60.000000,470.000000,148.000000,47.000000,384.000000,6037.000000,1.000000,1.000000,0.000000,0.000000,2.000000,3.333938e+07,-1.194484e+08,1.290000e+02,1.0,64.000000,1.0,1.0,1.0,31.00000,6.037101e+07,3491.000000,1286.000000,6952.000000,95982.000000,0.000000,7.0,1.000000,6.0,1.000000,24.000000,14.000000,1862.000000,1.000000,5.000000e+00,8.000000e+00,2003.000000,4.000000e+00,8.300000e+00,6.000000,6.037101e+13
25%,1.152380e+07,1.000000,7.000000,221.000000,2.000000,2.000000,4.000000,5.000000,2.000000,66.0,1011.000000,1218.000000,1200.000000,1000.000000,1696.000000,1012.500000,1184.000000,6037.000000,1.000000,2.000000,2.000000,308.500000,2.000000,3.384587e+07,-1.184240e+08,5.710000e+03,1.0,440.000000,1.0,1.0,1.0,261.00000,6.037301e+07,12447.000000,2061.000000,41131.000000,96173.000000,0.000000,7.0,1.000000,6.0,1.000000,180.000000,99.000000,1950.000000,1.000000,7.857925e+04,1.859770e+05,2016.000000,7.722900e+04,2.451550e+03,14.000000,6.037301e+13
50%,1.243270e+07,1.000000,7.000000,547.000000,2.000000,3.000000,4.000000,6.000000,2.000000,66.0,1284.000000,1580.000000,1547.000000,1296.000000,2169.000000,1285.000000,1978.000000,6037.000000,1.000000,2.000000,2.000000,441.000000,2.000000,3.402985e+07,-1.182067e+08,7.024000e+03,1.0,500.000000,1.0,1.0,1.0,261.00000,6.037571e+07,24832.000000,3101.000000,118208.000000,96375.000000,0.000000,7.0,1.000000,6.0,1.000000,260.000000,196.000000,1963.000000,1.000000,1.287145e+05,3.203450e+05,2016.000000,1.748550e+05,3.991790e+03,14.000000,6.037571e+13
75%,1.408074e+07,1.000000,7.000000,721.500000,3.000000,4.000000,4.000000,8.000000,3.000000,66.0,1610.000000,2147.000000,2081.000000,1440.000000,2960.000000,1612.000000,3304.000000,6059.000000,1.000000,3.000000,2.000000,494.000000,7.000000,3.417731e+07,-1.179700e+08,1.000000e+04,1.0,593.500000,1.0,1.0,1.0,261.00000,6.059042e+07,45457.000000,3101.000000,274684.000000,96974.000000,0.000000,7.0,1.000000,6.0,1.000000,378.500000,330.000000,1981.000000,2.000000,2.059528e+05,5.147350e+05,2016.000000,3.252965e+05,6.215930e+03,15.000000,6.059042e+13
max,1.696019e+08,13.000000,21.000000,1572.000000,20.000000,25.000000,5.000000,12.000000,20.000000,66.0,15998.000000,161232.000000,26345.000000,2400.000000,161232.000000,15998.000000,15341.000000,6111.000000,9.000000,20.000000,12.000000,3598.000000,24.000000,3.480695e+07,-1.175559e+08,6.971010e+06,1.0,2176.000000,1.0,1.0,1.0,275.00000,6.111009e+07,396556.000000,3101.000000,764167.000000,399675.000000,86.000000,7.0,4.000000,6.0,199.000000,6407.000000,1320.000000,2016.000000,4.000000,6.640493e+07,6.750649e+07,2016.000000,2.210127e+07,1.195296e+06,15.000000,6.111009e+13

In [8]:
df.duplicated().sum()

0

In [9]:
df.isnull().sum()

parcelid                            0
airconditioningtypeid           36047
architecturalstyletypeid        49902
basementsqft                    49970
bathroomcnt                         0
bedroomcnt                          0
buildingclasstypeid             49742
buildingqualitytypeid           16920
calculatedbathnbr                2104
decktypeid                      49660
finishedfloor1squarefeet        46069
calculatedfinishedsquarefeet      705
finishedsquarefeet12             4389
finishedsquarefeet13            49842
finishedsquarefeet15            46797
finishedsquarefeet50            46069
finishedsquarefeet6             49677
fips                                0
fireplacecnt                    44664
fullbathcnt                      2104
garagecarcnt                    35682
garagetotalsqft                 35682
hashottuborspa                  49240
heatingorsystemtypeid           18283
latitude                            0
longitude                           0
lotsizesquarefeet                4392
poolcnt                         40744
poolsizesum                     49500
pooltypeid10                    49753
pooltypeid2                     49487
pooltypeid7                     41268
propertycountylandusecode           1
propertylandusetypeid               0
propertyzoningdesc              16216
rawcensustractandblock              0
regionidcity                      951
regionidcounty                      0
regionidneighborhood            29891
regionidzip                       176
roomcnt                             1
storytypeid                     49970
threequarterbathnbr             44966
typeconstructiontypeid          49898
unitcnt                         16288
yardbuildingsqft17              48389
yardbuildingsqft26              49952
yearbuilt                         746
numberofstories                 38776
fireplaceflag                   49921
structuretaxvaluedollarcnt        860
taxvaluedollarcnt                 615
assessmentyear                      0
landtaxvaluedollarcnt            1041
taxamount                         337
taxdelinquencyflag              49015
taxdelinquencyyear              49015
censustractandblock              1409
dtype: int64

In [10]:
df.nunique()

parcelid                        50000
airconditioningtypeid               5
architecturalstyletypeid            4
basementsqft                       30
bathroomcnt                        26
bedroomcnt                         16
buildingclasstypeid                 5
buildingqualitytypeid              12
calculatedbathnbr                  25
decktypeid                          1
finishedfloor1squarefeet         1486
calculatedfinishedsquarefeet     4648
finishedsquarefeet12             4382
finishedsquarefeet13               52
finishedsquarefeet15             1885
finishedsquarefeet50             1497
finishedsquarefeet6               304
fips                                3
fireplacecnt                        7
fullbathcnt                        16
garagecarcnt                       13
garagetotalsqft                   726
hashottuborspa                      1
heatingorsystemtypeid               9
latitude                        45189
longitude                       43885
lotsizesquarefeet               15380
poolcnt                             1
poolsizesum                       185
pooltypeid10                        1
pooltypeid2                         1
pooltypeid7                         1
propertycountylandusecode          99
propertylandusetypeid              15
propertyzoningdesc               1774
rawcensustractandblock          34667
regionidcity                      175
regionidcounty                      3
regionidneighborhood              477
regionidzip                       386
roomcnt                            20
storytypeid                         1
threequarterbathnbr                 4
typeconstructiontypeid              1
unitcnt                            24
yardbuildingsqft17                449
yardbuildingsqft26                 44
yearbuilt                         133
numberofstories                     4
fireplaceflag                       1
structuretaxvaluedollarcnt      36033
taxvaluedollarcnt               38430
assessmentyear                      4
landtaxvaluedollarcnt           34891
taxamount                       48128
taxdelinquencyflag                  1
taxdelinquencyyear                 10
censustractandblock             34135
dtype: int64

In [11]:
for column in df.columns:
    if df[column].nunique() <= 10:
        print(f"Column: {column} {df[column].unique()}")

Column: airconditioningtypeid [nan  1. 13.  9.  5. 11.]
Column: architecturalstyletypeid [nan  7. 21.  8.  2.]
Column: buildingclasstypeid [nan  5.  3.  4.  2.  1.]
Column: decktypeid [nan 66.]
Column: fips [6037 6059 6111]
Column: fireplacecnt [nan  3.  1.  2.  4.  9.  5.  7.]
Column: hashottuborspa [nan True]
Column: heatingorsystemtypeid [nan  2.  7. 20.  6. 13. 18. 24. 12. 10.]
Column: poolcnt [nan  1.]
Column: pooltypeid10 [nan  1.]
Column: pooltypeid2 [nan  1.]
Column: pooltypeid7 [nan  1.]
Column: regionidcounty [3101 1286 2061]
Column: storytypeid [nan  7.]
Column: threequarterbathnbr [nan  1.  2.  4.  3.]
Column: typeconstructiontypeid [nan  6.]
Column: numberofstories [nan  1.  4.  2.  3.]
Column: fireplaceflag [nan True]
Column: assessmentyear [2016 2015 2014 2003]
Column: taxdelinquencyflag [nan 'Y']
Column: taxdelinquencyyear [nan 13. 15. 11. 14.  9. 10.  8. 12.  7.  6.]